export { default as Badge } from './Badge/Badge'
export { default as Button } from "./Button/Button";
export { default as ChalkBoard } from "./ChalkBoard/ChalkBoard";
export { default as Header } from "./Header/Header";
export { default as InputContainer } from "./InputContainer/InputContainer";
export { default as Keyboard } from "./Keyboard/Keyboard";
export { default as CustomModal } from "./CustomModal/CustomModal";
export { default as Notification } from "./Notification/Notification";
export { default as StickMan } from "./StickMan/StickMan";
export { default as WordContainer } from "./WordContainer/WordContainer";
export { default as AboutMe } from "./AboutMe/AboutMe";
